rtabmap: 
  rtabmap:
    frame_id: "base_link"
    odom_frame_id: "odom"
    queue_size: 10

    subscribe_depth: false
    subscribe_rgb: false
    subscribe_rgbd: true
    subscribe_odom_info: false
    
    Grid:
      CellSize: 0.05
      MaxGroundHeight: 0.05
      MaxObstacleHeight: 1.0
      
    GridGlobal:
      Eroded: true

    Kp:
      MaxDepth: 4
      RoiRatios: "0.0 0.0 0.3 0.1"

    RGBD:
      AngularUpdate: 0.0
      LinearUpdate: 0.0
      OptimizeFromGraphEnd: false
      OptimizeMaxError: 32

    Reg:
      Force3DoF: true


